modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-v2.1"
updateJSONURL="https://tophatcat.dev/kiris-lib/update.json"
issueTrackerURL="https://github.com/TopHatCats-Mods/kiris-lib/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kiris-lib"
credits="KiriCattus"
authors="KiriCattus"
#logoFile=""

[[mods]]
modId="kirislib"
version="${file.jarVersion}"
displayName="Kiri's Lib"
description='''
A library mod for my other mods.
'''

[[dependencies.kirislib]]
   modId="forge"
   mandatory=true
   versionRange="[37,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kirislib]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1]"
   ordering="NONE"
   side="BOTH"
